language: cpp

addons:
  apt:
    packages:
      - g++-6
      - clang
    sources: &sources
      - ubuntu-toolchain-r-test

install:
- wget --no-check-certificate https://cmake.org/files/v3.7/cmake-3.7.1-Linux-x86_64.tar.gz
- tar -xzf cmake-3.7.1-Linux-x86_64.tar.gz
- export CMAKEDIR=$TRAVIS_BUILD_DIR/cmake-3.7.1-Linux-x86_64/bin/cmake

script:
- mkdir build

- cd build/
- $CMAKEDIR CMAKE_CXX_COMPILER=g++6 -DUSE_CLANG=0 -DCMAKE_BUILD_TYPE="Release" -G "Unix Makefiles" ..
- make
- if [[ $? -ne 0 ]]; then exit 1; fi
- cd ..

- rm -rf build
- mkdir build

- cd build/
- $CMAKEDIR -DUSE_CLANG=1 -DCMAKE_BUILD_TYPE="Release" -G "Unix Makefiles" ..
- make
-  if [[ $? -ne 0 ]]; then exit 1; fi
- cd ..
